### PR TITLE
Support ZonedDateTime

### LINKED ISSUE #19: Support ZonedDateTime
This needs a `promote_rule` to support ZonedDateTime promotion from `TimeZones.jl`

`Base.promote_rule(::Type{InfExtendedTime{T}}, ::Type{S}) where {T<:TimeType, S<:ZonedDateTime} = InfExtendedTime(promote_type(T, S))`

### PR DESCRIPTION
**Pull request by fchorney**
Closes #19

### CODE REVIEW

**Comment by cjdoris** [comment]
Can you use `Requires.jl` to remove the dependency on `ZonedDateTime.jl`? I'd rather only depend on things truly required for the core functionality.

Perhaps put an `__init__` function in `init.jl`, which does
```julia
@require ZonedDateTime="..." include("zoneddatetime.jl")
```

**Comment by fchorney** [comment]
oh interesting. Yeah I'll look into using `Requires`

**Comment by fchorney** [comment]
Not sure if there is a better way to do the tests, or if this is good?

**Comment by cjdoris** [comment]
Looks good, yes I'm happy with any dependencies for testing.

**Comment by fchorney** [comment]
@cjdoris thanks for letting me do all these PR's! Are the last few going to be registered as `0.2.1`?

**Comment by cjdoris** [comment]
Yes I'll register it now. Thanks for your contributions!

**Pull request merged**
